stages:
  - test

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"

cache:
  key: "$CI_COMMIT_REF_SLUG"
  paths:
    - .m2/repository
    - target/

before_script:
  - apt-get update -yqq
  - apt-get install -yqq openjdk-17-jdk maven
  - java -version
  - mvn -version

# Define the test job
Test:
  stage: test
  tags:
    - pmpeople
  image: maven:3.9.4-eclipse-temurin-17
  script:
    - mvn clean test
  only:
    - MPOS
