name: Java CI with Selenium and EdgeDriver

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      JAVA_HOME: /usr/lib/jvm/java-17-openjdk-amd64
      MAVEN_OPTS: "-Dmaven.repo.local=$GITHUB_WORKSPACE/.m2/repository"

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      # Step 3: Install Microsoft Edge and EdgeDriver
      - name: Install Microsoft Edge and EdgeDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y microsoft-edge-stable || echo "Edge is already installed"
          
          # Detect Microsoft Edge version
          EDGE_VERSION=$(microsoft-edge --version | grep -oP '\d+\.\d+\.\d+\.\d+')
          if [ -z "$EDGE_VERSION" ]; then
            echo "Failed to detect Microsoft Edge version."
            exit 1
          fi
          echo "Detected Microsoft Edge version: $EDGE_VERSION"
          
          # Fetch EdgeDriver version
          DRIVER_VERSION=$(curl -s "https://msedgedriver.azureedge.net/LATEST_RELEASE_$EDGE_VERSION")
          if [ -z "$DRIVER_VERSION" ]; then
            echo "Failed to fetch EdgeDriver version for Edge $EDGE_VERSION."
            exit 1
          fi
          echo "Resolved EdgeDriver version: $DRIVER_VERSION"
          
          # Download and install EdgeDriver
          DRIVER_URL="https://msedgedriver.azureedge.net/$DRIVER_VERSION/edgedriver_linux64.zip"
          curl -s -L -o msedgedriver.zip "$DRIVER_URL"
          if [ $? -ne 0 ]; then
            echo "Failed to download EdgeDriver from $DRIVER_URL."
            exit 1
          fi
          unzip -o msedgedriver.zip -d /usr/bin/
          sudo chmod +x /usr/bin/edgedriver
          rm msedgedriver.zip
          microsoft-edge --version
          edgedriver --version

      # Step 4: Set up Maven and run tests
      - name: Run Tests
        run: |
          mvn clean test
          mvn install
