name: Java CI with Selenium and Chromedriver

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      JAVA_HOME: /usr/lib/jvm/java-17-openjdk-amd64
      MAVEN_OPTS: "-Dmaven.repo.local=$GITHUB_WORKSPACE/.m2/repository"

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      # Step 3: Install Google Chrome and Chromedriver
      - name: Install Chrome and Chromedriver
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
          sudo apt-get install -y chromium-chromedriver
          echo 'Adding Chromedriver to PATH...'
          sudo ln -s /usr/lib/chromium-browser/chromedriver /usr/bin/chromedriver
          google-chrome --version
          chromedriver --version

      # Step 4: Set up Maven and run tests
      - name: Run Tests
        run: |
          mvn clean test
