name: Java CI with Selenium and EdgeDriver

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      JAVA_HOME: /usr/lib/jvm/java-17-openjdk-amd64
      MAVEN_OPTS: "-Dmaven.repo.local=$GITHUB_WORKSPACE/.m2/repository"

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      # Step 3: Install Microsoft Edge and EdgeDriver
      - name: Install Microsoft Edge and EdgeDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y microsoft-edge-stable
          EDGE_VERSION=$(microsoft-edge --version | grep -oP '\d+\.\d+\.\d+\.\d+')
          DRIVER_VERSION=$(curl -s "https://msedgedriver.azureedge.net/LATEST_RELEASE_$EDGE_VERSION")
          curl -s -L -o msedgedriver.zip "https://msedgedriver.azureedge.net/$DRIVER_VERSION/edgedriver_linux64.zip"
          unzip msedgedriver.zip -d /usr/bin/
          rm msedgedriver.zip
          microsoft-edge --version
          edgedriver --version

      # Step 4: Set up Maven and run tests
      - name: Run Tests
        run: |
          mvn clean test
          mvn install
