name: Java CI with Selenium and FirefoxDriver

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      JAVA_HOME: /usr/lib/jvm/java-17-openjdk-amd64
      MAVEN_OPTS: "-Dmaven.repo.local=$GITHUB_WORKSPACE/.m2/repository"

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      # Step 3: Install Firefox and Geckodriver
      - name: Install Firefox and Geckodriver
        run: |
          sudo apt-get update
          sudo apt-get install -y firefox || echo "Firefox is already installed"
          
          # Fetch the latest Geckodriver release version
          GECKODRIVER_VERSION=$(curl -s https://api.github.com/repos/mozilla/geckodriver/releases/latest | grep 'tag_name' | cut -d '"' -f 4)
          if [ -z "$GECKODRIVER_VERSION" ]; then
            echo "Failed to fetch Geckodriver version."
            exit 1
          fi
          echo "Resolved Geckodriver version: $GECKODRIVER_VERSION"

          # Download and install Geckodriver
          DRIVER_URL="https://github.com/mozilla/geckodriver/releases/download/$GECKODRIVER_VERSION/geckodriver-$GECKODRIVER_VERSION-linux64.tar.gz"
          curl -s -L -o geckodriver.tar.gz "$DRIVER_URL"
          if [ $? -ne 0 ]; then
            echo "Failed to download Geckodriver from $DRIVER_URL."
            exit 1
          fi
          tar -xzf geckodriver.tar.gz -C /usr/bin/ --overwrite
          sudo chmod +x /usr/bin/geckodriver
          rm geckodriver.tar.gz
          firefox --version
          geckodriver --version

      # Step 4: Set up Maven and run tests
      - name: Run Tests
        run: |
          mvn clean test
          mvn install
