name: Java CI with JDK 17 and Chromedriver

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Set up JDK 17
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    # Install Chromedriver
    - name: Install Chromedriver
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-chromedriver
        echo 'Adding Chromedriver to PATH...'
        export PATH="$PATH:/usr/lib/chromium-browser/"
        chromedriver --version

    # Run Tests
    - name: Run Tests
      run: |
        mvn clean test
      env:
        JAVA_HOME: ${{ env.JAVA_HOME }}
